name: ci-dgo-tests

on:
  push:
    branches:
      - main
      - release/v240
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - release/v240

permissions:
  contents: read

jobs:
  dgo-tests:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - name: Checkout Dgraph repo
        uses: actions/checkout@v4
        with:
          path: dgraph
          repository: hypermodeinc/dgraph
          ref: main
      - name: Checkout Dgo repo
        uses: actions/checkout@v4
        with:
          path: dgo
          repository: hypermodeinc/dgo
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: dgo/go.mod
      - name: Make Linux Build and Docker Image
        run: cd dgraph && make docker-image
      - name: Move dgraph binary to gopath
        run: cd dgraph && mv dgraph/dgraph ~/go/bin/dgraph
      - name: Clean Up Test Cache
        run: go clean -testcache
      - name: Run dgo client tests
        run: |
          #!/bin/bash
          cd dgo
          # go env settings
          export GOPATH=~/go
          docker compose -f t/docker-compose.yml up -d
          echo "Waiting for cluster to be healthy..."
          sleep 20
          echo "Running dgo tests..."
          go test -v ./...
          docker compose -f t/docker-compose.yml down
